// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XW8dJBbO1peMLSs2XY6R8IgIGzPKWc4',
    appId: '1:64516111213:web:d429ac85cbf126397e3864',
    messagingSenderId: '64516111213',
    projectId: 'khoanubu',
    authDomain: 'khoanubu.firebaseapp.com',
    databaseURL: 'https://khoanubu-default-rtdb.firebaseio.com',
    storageBucket: 'khoanubu.appspot.com',
    measurementId: 'G-YSG26WYRWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXR6myPJSxe3Ls1l-g-DVgUOMIy1_1hc',
    appId: '1:64516111213:android:76d62f00ad5392067e3864',
    messagingSenderId: '64516111213',
    projectId: 'khoanubu',
    databaseURL: 'https://khoanubu-default-rtdb.firebaseio.com',
    storageBucket: 'khoanubu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhu3kRpajrxOp7cYqkxkX4r4JbPzUA3s',
    appId: '1:64516111213:ios:5c56535aab20deee7e3864',
    messagingSenderId: '64516111213',
    projectId: 'khoanubu',
    databaseURL: 'https://khoanubu-default-rtdb.firebaseio.com',
    storageBucket: 'khoanubu.appspot.com',
    androidClientId: '64516111213-9oebe5sa22v7efe4240dinm1qkdv0865.apps.googleusercontent.com',
    iosClientId: '64516111213-afm7s4shdl18ppcsjdbb66thq8pv7vb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokAppPoly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhu3kRpajrxOp7cYqkxkX4r4JbPzUA3s',
    appId: '1:64516111213:ios:12644816e44328617e3864',
    messagingSenderId: '64516111213',
    projectId: 'khoanubu',
    databaseURL: 'https://khoanubu-default-rtdb.firebaseio.com',
    storageBucket: 'khoanubu.appspot.com',
    androidClientId: '64516111213-9oebe5sa22v7efe4240dinm1qkdv0865.apps.googleusercontent.com',
    iosClientId: '64516111213-h215heb8o304iiuoi3bdfvs9p3ukceqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokAppPoly.RunnerTests',
  );
}
